class INPUT_FIELDS:
    """Class for keeping track field names"""
    ticker = "ticker"
    industry = "industry"
    trailing_pe = "trailing_pe"
    forward_pe = "forward_pe"
    analyst_direction = "analyst_direction"
    analyst_target_price = "analyst_target_price"
    analyst_conviction = "analyst_conviction"
    sentiment_score = "sentiment_score"
    sentiment_direction = "sentiment_direction"
    sentiment_conviction = "sentiment_conviction"
    execution_time = "execution_time"
    valid_period = "valid_period"